/*
 * generated by Xtext 2.29.0
 */
package n7.intern.v3.xtext.idsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractIDslScopeProvider extends DelegatingScopeProvider {
}
