/*
 * generated by Xtext 2.29.0
 */
package n7.intern.v3.xtext.idsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import n7.intern.v3.xtext.idsl.ide.contentassist.antlr.internal.InternalIDslParser;
import n7.intern.v3.xtext.idsl.services.IDslGrammarAccess;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class IDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(IDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, IDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getIotFrameworkAccess().getAlternatives_0(), "rule__IotFramework__Alternatives_0");
			builder.put(grammarAccess.getIotFrameworkAccess().getAlternatives_5(), "rule__IotFramework__Alternatives_5");
			builder.put(grammarAccess.getThingBlockAccess().getAlternatives_4(), "rule__ThingBlock__Alternatives_4");
			builder.put(grammarAccess.getParameterExpressionAccess().getAlternatives_2(), "rule__ParameterExpression__Alternatives_2");
			builder.put(grammarAccess.getHolderBlockAccess().getAlternatives_4(), "rule__HolderBlock__Alternatives_4");
			builder.put(grammarAccess.getPreProcessorBlockAccess().getAlternatives_4(), "rule__PreProcessorBlock__Alternatives_4");
			builder.put(grammarAccess.getPreProcessorBlockAccess().getAlternatives_8(), "rule__PreProcessorBlock__Alternatives_8");
			builder.put(grammarAccess.getDataProcessorBlockAccess().getAlternatives_4(), "rule__DataProcessorBlock__Alternatives_4");
			builder.put(grammarAccess.getDataProcessorBlockAccess().getAlternatives_8(), "rule__DataProcessorBlock__Alternatives_8");
			builder.put(grammarAccess.getSynchronizerBlockAccess().getAlternatives_4(), "rule__SynchronizerBlock__Alternatives_4");
			builder.put(grammarAccess.getSynchronizerBlockAccess().getAlternatives_8(), "rule__SynchronizerBlock__Alternatives_8");
			builder.put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
			builder.put(grammarAccess.getIotFrameworkAccess().getGroup(), "rule__IotFramework__Group__0");
			builder.put(grammarAccess.getIotFrameworkAccess().getGroup_1(), "rule__IotFramework__Group_1__0");
			builder.put(grammarAccess.getThingBlockAccess().getGroup(), "rule__ThingBlock__Group__0");
			builder.put(grammarAccess.getThingBlockAccess().getGroup_0(), "rule__ThingBlock__Group_0__0");
			builder.put(grammarAccess.getConnexionBlockAccess().getGroup(), "rule__ConnexionBlock__Group__0");
			builder.put(grammarAccess.getConnexionBlockAccess().getGroup_0(), "rule__ConnexionBlock__Group_0__0");
			builder.put(grammarAccess.getParameterExpressionAccess().getGroup(), "rule__ParameterExpression__Group__0");
			builder.put(grammarAccess.getStreamDefinitionAccess().getGroup(), "rule__StreamDefinition__Group__0");
			builder.put(grammarAccess.getStreamDefinitionAccess().getGroup_0(), "rule__StreamDefinition__Group_0__0");
			builder.put(grammarAccess.getOutputBlockAccess().getGroup(), "rule__OutputBlock__Group__0");
			builder.put(grammarAccess.getOutputBlockAccess().getGroup_0(), "rule__OutputBlock__Group_0__0");
			builder.put(grammarAccess.getHolderBlockAccess().getGroup(), "rule__HolderBlock__Group__0");
			builder.put(grammarAccess.getHolderBlockAccess().getGroup_0(), "rule__HolderBlock__Group_0__0");
			builder.put(grammarAccess.getAnonymousStreamDefinitionAccess().getGroup(), "rule__AnonymousStreamDefinition__Group__0");
			builder.put(grammarAccess.getAnomynousHolderAccess().getGroup(), "rule__AnomynousHolder__Group__0");
			builder.put(grammarAccess.getAnomynousHolderAccess().getGroup_1(), "rule__AnomynousHolder__Group_1__0");
			builder.put(grammarAccess.getPreProcessorBlockAccess().getGroup(), "rule__PreProcessorBlock__Group__0");
			builder.put(grammarAccess.getPreProcessorBlockAccess().getGroup_0(), "rule__PreProcessorBlock__Group_0__0");
			builder.put(grammarAccess.getPreProcessorBlockAccess().getGroup_4_0(), "rule__PreProcessorBlock__Group_4_0__0");
			builder.put(grammarAccess.getPreProcessorBlockAccess().getGroup_4_0_0(), "rule__PreProcessorBlock__Group_4_0_0__0");
			builder.put(grammarAccess.getPreProcessorBlockAccess().getGroup_5(), "rule__PreProcessorBlock__Group_5__0");
			builder.put(grammarAccess.getPreProcessorBlockAccess().getGroup_8_0(), "rule__PreProcessorBlock__Group_8_0__0");
			builder.put(grammarAccess.getPreProcessorBlockAccess().getGroup_8_0_0(), "rule__PreProcessorBlock__Group_8_0_0__0");
			builder.put(grammarAccess.getPreProcessorBlockAccess().getGroup_9(), "rule__PreProcessorBlock__Group_9__0");
			builder.put(grammarAccess.getDataProcessorBlockAccess().getGroup(), "rule__DataProcessorBlock__Group__0");
			builder.put(grammarAccess.getDataProcessorBlockAccess().getGroup_0(), "rule__DataProcessorBlock__Group_0__0");
			builder.put(grammarAccess.getDataProcessorBlockAccess().getGroup_4_0(), "rule__DataProcessorBlock__Group_4_0__0");
			builder.put(grammarAccess.getDataProcessorBlockAccess().getGroup_4_0_0(), "rule__DataProcessorBlock__Group_4_0_0__0");
			builder.put(grammarAccess.getDataProcessorBlockAccess().getGroup_5(), "rule__DataProcessorBlock__Group_5__0");
			builder.put(grammarAccess.getDataProcessorBlockAccess().getGroup_8_0(), "rule__DataProcessorBlock__Group_8_0__0");
			builder.put(grammarAccess.getDataProcessorBlockAccess().getGroup_8_0_0(), "rule__DataProcessorBlock__Group_8_0_0__0");
			builder.put(grammarAccess.getDataProcessorBlockAccess().getGroup_9(), "rule__DataProcessorBlock__Group_9__0");
			builder.put(grammarAccess.getSynchronizerBlockAccess().getGroup(), "rule__SynchronizerBlock__Group__0");
			builder.put(grammarAccess.getSynchronizerBlockAccess().getGroup_0(), "rule__SynchronizerBlock__Group_0__0");
			builder.put(grammarAccess.getSynchronizerBlockAccess().getGroup_4_0(), "rule__SynchronizerBlock__Group_4_0__0");
			builder.put(grammarAccess.getSynchronizerBlockAccess().getGroup_4_0_0(), "rule__SynchronizerBlock__Group_4_0_0__0");
			builder.put(grammarAccess.getSynchronizerBlockAccess().getGroup_5(), "rule__SynchronizerBlock__Group_5__0");
			builder.put(grammarAccess.getSynchronizerBlockAccess().getGroup_8_0(), "rule__SynchronizerBlock__Group_8_0__0");
			builder.put(grammarAccess.getSynchronizerBlockAccess().getGroup_8_0_0(), "rule__SynchronizerBlock__Group_8_0_0__0");
			builder.put(grammarAccess.getSynchronizerBlockAccess().getGroup_9(), "rule__SynchronizerBlock__Group_9__0");
			builder.put(grammarAccess.getDefinitionInstructionAccess().getGroup(), "rule__DefinitionInstruction__Group__0");
			builder.put(grammarAccess.getDefinitionInstructionAccess().getGroup_2(), "rule__DefinitionInstruction__Group_2__0");
			builder.put(grammarAccess.getPreProcessorAssignationAccess().getGroup(), "rule__PreProcessorAssignation__Group__0");
			builder.put(grammarAccess.getPreProcessorAssignationAccess().getGroup_0(), "rule__PreProcessorAssignation__Group_0__0");
			builder.put(grammarAccess.getPreProcessorAssignationAccess().getGroup_4(), "rule__PreProcessorAssignation__Group_4__0");
			builder.put(grammarAccess.getProcessorAssignationAccess().getGroup(), "rule__ProcessorAssignation__Group__0");
			builder.put(grammarAccess.getProcessorAssignationAccess().getGroup_0(), "rule__ProcessorAssignation__Group_0__0");
			builder.put(grammarAccess.getProcessorAssignationAccess().getGroup_4(), "rule__ProcessorAssignation__Group_4__0");
			builder.put(grammarAccess.getSynchronizerAssignationAccess().getGroup(), "rule__SynchronizerAssignation__Group__0");
			builder.put(grammarAccess.getSynchronizerAssignationAccess().getGroup_0(), "rule__SynchronizerAssignation__Group_0__0");
			builder.put(grammarAccess.getSynchronizerAssignationAccess().getGroup_4(), "rule__SynchronizerAssignation__Group_4__0");
			builder.put(grammarAccess.getOutputAssignationAccess().getGroup(), "rule__OutputAssignation__Group__0");
			builder.put(grammarAccess.getOutputAssignationAccess().getGroup_0(), "rule__OutputAssignation__Group_0__0");
			builder.put(grammarAccess.getOutputAssignationAccess().getGroup_3(), "rule__OutputAssignation__Group_3__0");
			builder.put(grammarAccess.getDomainParameterBlockAccess().getGroup(), "rule__DomainParameterBlock__Group__0");
			builder.put(grammarAccess.getDomainParameterBlockAccess().getGroup_4(), "rule__DomainParameterBlock__Group_4__0");
			builder.put(grammarAccess.getIotFrameworkAccess().getDataflowdescriptorsAssignment_0_0(), "rule__IotFramework__DataflowdescriptorsAssignment_0_0");
			builder.put(grammarAccess.getIotFrameworkAccess().getDataflowdescriptorsAssignment_0_1(), "rule__IotFramework__DataflowdescriptorsAssignment_0_1");
			builder.put(grammarAccess.getIotFrameworkAccess().getDataflowdescriptorsAssignment_0_2(), "rule__IotFramework__DataflowdescriptorsAssignment_0_2");
			builder.put(grammarAccess.getIotFrameworkAccess().getInterfacerdescriptorsAssignment_0_3(), "rule__IotFramework__InterfacerdescriptorsAssignment_0_3");
			builder.put(grammarAccess.getIotFrameworkAccess().getInterfacerdescriptorsAssignment_0_4(), "rule__IotFramework__InterfacerdescriptorsAssignment_0_4");
			builder.put(grammarAccess.getIotFrameworkAccess().getInterfacerdescriptorsAssignment_0_5(), "rule__IotFramework__InterfacerdescriptorsAssignment_0_5");
			builder.put(grammarAccess.getIotFrameworkAccess().getDescriptionAssignment_1_2(), "rule__IotFramework__DescriptionAssignment_1_2");
			builder.put(grammarAccess.getIotFrameworkAccess().getNameAssignment_3(), "rule__IotFramework__NameAssignment_3");
			builder.put(grammarAccess.getIotFrameworkAccess().getDataflowsAssignment_5_0(), "rule__IotFramework__DataflowsAssignment_5_0");
			builder.put(grammarAccess.getIotFrameworkAccess().getInterfacersAssignment_5_1(), "rule__IotFramework__InterfacersAssignment_5_1");
			builder.put(grammarAccess.getIotFrameworkAccess().getInterfacersAssignment_5_2(), "rule__IotFramework__InterfacersAssignment_5_2");
			builder.put(grammarAccess.getIotFrameworkAccess().getInterfacersAssignment_5_3(), "rule__IotFramework__InterfacersAssignment_5_3");
			builder.put(grammarAccess.getIotFrameworkAccess().getInterfacersAssignment_5_4(), "rule__IotFramework__InterfacersAssignment_5_4");
			builder.put(grammarAccess.getThingBlockAccess().getDescriptionAssignment_0_2(), "rule__ThingBlock__DescriptionAssignment_0_2");
			builder.put(grammarAccess.getThingBlockAccess().getNameAssignment_2(), "rule__ThingBlock__NameAssignment_2");
			builder.put(grammarAccess.getThingBlockAccess().getConnexionsAssignment_4_0(), "rule__ThingBlock__ConnexionsAssignment_4_0");
			builder.put(grammarAccess.getThingBlockAccess().getParametersAssignment_4_1(), "rule__ThingBlock__ParametersAssignment_4_1");
			builder.put(grammarAccess.getThingBlockAccess().getStreamdescriptorsAssignment_4_2(), "rule__ThingBlock__StreamdescriptorsAssignment_4_2");
			builder.put(grammarAccess.getConnexionBlockAccess().getDescriptionAssignment_0_2(), "rule__ConnexionBlock__DescriptionAssignment_0_2");
			builder.put(grammarAccess.getConnexionBlockAccess().getNameAssignment_2(), "rule__ConnexionBlock__NameAssignment_2");
			builder.put(grammarAccess.getConnexionBlockAccess().getParametersAssignment_4(), "rule__ConnexionBlock__ParametersAssignment_4");
			builder.put(grammarAccess.getParameterExpressionAccess().getNameAssignment_0(), "rule__ParameterExpression__NameAssignment_0");
			builder.put(grammarAccess.getParameterExpressionAccess().getContentAssignment_2_0(), "rule__ParameterExpression__ContentAssignment_2_0");
			builder.put(grammarAccess.getParameterExpressionAccess().getContentAssignment_2_1(), "rule__ParameterExpression__ContentAssignment_2_1");
			builder.put(grammarAccess.getParameterExpressionAccess().getContentAssignment_2_2(), "rule__ParameterExpression__ContentAssignment_2_2");
			builder.put(grammarAccess.getParameterExpressionAccess().getContentAssignment_2_3(), "rule__ParameterExpression__ContentAssignment_2_3");
			builder.put(grammarAccess.getParameterExpressionAccess().getContentAssignment_2_4(), "rule__ParameterExpression__ContentAssignment_2_4");
			builder.put(grammarAccess.getParameterExpressionAccess().getContentAssignment_2_5(), "rule__ParameterExpression__ContentAssignment_2_5");
			builder.put(grammarAccess.getParameterExpressionAccess().getContentAssignment_2_6(), "rule__ParameterExpression__ContentAssignment_2_6");
			builder.put(grammarAccess.getParameterExpressionAccess().getContentAssignment_2_7(), "rule__ParameterExpression__ContentAssignment_2_7");
			builder.put(grammarAccess.getParameterExpressionAccess().getContentAssignment_2_8(), "rule__ParameterExpression__ContentAssignment_2_8");
			builder.put(grammarAccess.getStreamDefinitionAccess().getDescriptionAssignment_0_2(), "rule__StreamDefinition__DescriptionAssignment_0_2");
			builder.put(grammarAccess.getStreamDefinitionAccess().getNameAssignment_2(), "rule__StreamDefinition__NameAssignment_2");
			builder.put(grammarAccess.getStreamDefinitionAccess().getTypeAssignment_4(), "rule__StreamDefinition__TypeAssignment_4");
			builder.put(grammarAccess.getStreamDefinitionAccess().getSamplingRateAssignment_6(), "rule__StreamDefinition__SamplingRateAssignment_6");
			builder.put(grammarAccess.getOutputBlockAccess().getDescriptionAssignment_0_2(), "rule__OutputBlock__DescriptionAssignment_0_2");
			builder.put(grammarAccess.getOutputBlockAccess().getNameAssignment_2(), "rule__OutputBlock__NameAssignment_2");
			builder.put(grammarAccess.getOutputBlockAccess().getParametersAssignment_4(), "rule__OutputBlock__ParametersAssignment_4");
			builder.put(grammarAccess.getHolderBlockAccess().getDescriptionAssignment_0_2(), "rule__HolderBlock__DescriptionAssignment_0_2");
			builder.put(grammarAccess.getHolderBlockAccess().getNameAssignment_2(), "rule__HolderBlock__NameAssignment_2");
			builder.put(grammarAccess.getHolderBlockAccess().getParametersAssignment_4_0(), "rule__HolderBlock__ParametersAssignment_4_0");
			builder.put(grammarAccess.getHolderBlockAccess().getStreamdescriptorsAssignment_4_1(), "rule__HolderBlock__StreamdescriptorsAssignment_4_1");
			builder.put(grammarAccess.getAnonymousStreamDefinitionAccess().getNameAssignment_1(), "rule__AnonymousStreamDefinition__NameAssignment_1");
			builder.put(grammarAccess.getAnonymousStreamDefinitionAccess().getTypeAssignment_3(), "rule__AnonymousStreamDefinition__TypeAssignment_3");
			builder.put(grammarAccess.getAnomynousHolderAccess().getStreamdescriptorsAssignment_1_0(), "rule__AnomynousHolder__StreamdescriptorsAssignment_1_0");
			builder.put(grammarAccess.getAnomynousHolderAccess().getStreamdescriptorsAssignment_2(), "rule__AnomynousHolder__StreamdescriptorsAssignment_2");
			builder.put(grammarAccess.getReferenceNameAccess().getNameAssignment(), "rule__ReferenceName__NameAssignment");
			builder.put(grammarAccess.getPreProcessorBlockAccess().getDescriptionAssignment_0_2(), "rule__PreProcessorBlock__DescriptionAssignment_0_2");
			builder.put(grammarAccess.getPreProcessorBlockAccess().getNameAssignment_2(), "rule__PreProcessorBlock__NameAssignment_2");
			builder.put(grammarAccess.getPreProcessorBlockAccess().getInputdataflowdescriptorsAssignment_4_0_0_0(), "rule__PreProcessorBlock__InputdataflowdescriptorsAssignment_4_0_0_0");
			builder.put(grammarAccess.getPreProcessorBlockAccess().getInputdataflowdescriptorsAssignment_4_0_1(), "rule__PreProcessorBlock__InputdataflowdescriptorsAssignment_4_0_1");
			builder.put(grammarAccess.getPreProcessorBlockAccess().getInputdataflowdescriptorsAssignment_4_1(), "rule__PreProcessorBlock__InputdataflowdescriptorsAssignment_4_1");
			builder.put(grammarAccess.getPreProcessorBlockAccess().getAnomynousinputdataflowdescriptorsAssignment_4_2(), "rule__PreProcessorBlock__AnomynousinputdataflowdescriptorsAssignment_4_2");
			builder.put(grammarAccess.getPreProcessorBlockAccess().getAnomynousinputdataflowdescriptorsAssignment_5_1(), "rule__PreProcessorBlock__AnomynousinputdataflowdescriptorsAssignment_5_1");
			builder.put(grammarAccess.getPreProcessorBlockAccess().getOutputdataflowdescriptorsAssignment_8_0_0_0(), "rule__PreProcessorBlock__OutputdataflowdescriptorsAssignment_8_0_0_0");
			builder.put(grammarAccess.getPreProcessorBlockAccess().getOutputdataflowdescriptorsAssignment_8_0_1(), "rule__PreProcessorBlock__OutputdataflowdescriptorsAssignment_8_0_1");
			builder.put(grammarAccess.getPreProcessorBlockAccess().getOutputdataflowdescriptorsAssignment_8_1(), "rule__PreProcessorBlock__OutputdataflowdescriptorsAssignment_8_1");
			builder.put(grammarAccess.getPreProcessorBlockAccess().getAnomynousoutputdataflowdescriptorsAssignment_8_2(), "rule__PreProcessorBlock__AnomynousoutputdataflowdescriptorsAssignment_8_2");
			builder.put(grammarAccess.getPreProcessorBlockAccess().getAnomynousoutputdataflowdescriptorsAssignment_9_1(), "rule__PreProcessorBlock__AnomynousoutputdataflowdescriptorsAssignment_9_1");
			builder.put(grammarAccess.getPreProcessorBlockAccess().getParametersAssignment_11(), "rule__PreProcessorBlock__ParametersAssignment_11");
			builder.put(grammarAccess.getDataProcessorBlockAccess().getDescriptionAssignment_0_2(), "rule__DataProcessorBlock__DescriptionAssignment_0_2");
			builder.put(grammarAccess.getDataProcessorBlockAccess().getNameAssignment_2(), "rule__DataProcessorBlock__NameAssignment_2");
			builder.put(grammarAccess.getDataProcessorBlockAccess().getInputdataflowdescriptorsAssignment_4_0_0_0(), "rule__DataProcessorBlock__InputdataflowdescriptorsAssignment_4_0_0_0");
			builder.put(grammarAccess.getDataProcessorBlockAccess().getInputdataflowdescriptorsAssignment_4_0_1(), "rule__DataProcessorBlock__InputdataflowdescriptorsAssignment_4_0_1");
			builder.put(grammarAccess.getDataProcessorBlockAccess().getInputdataflowdescriptorsAssignment_4_1(), "rule__DataProcessorBlock__InputdataflowdescriptorsAssignment_4_1");
			builder.put(grammarAccess.getDataProcessorBlockAccess().getAnomynousinputdataflowdescriptorsAssignment_4_2(), "rule__DataProcessorBlock__AnomynousinputdataflowdescriptorsAssignment_4_2");
			builder.put(grammarAccess.getDataProcessorBlockAccess().getAnomynousinputdataflowdescriptorsAssignment_5_1(), "rule__DataProcessorBlock__AnomynousinputdataflowdescriptorsAssignment_5_1");
			builder.put(grammarAccess.getDataProcessorBlockAccess().getOutputdataflowdescriptorsAssignment_8_0_0_0(), "rule__DataProcessorBlock__OutputdataflowdescriptorsAssignment_8_0_0_0");
			builder.put(grammarAccess.getDataProcessorBlockAccess().getOutputdataflowdescriptorsAssignment_8_0_1(), "rule__DataProcessorBlock__OutputdataflowdescriptorsAssignment_8_0_1");
			builder.put(grammarAccess.getDataProcessorBlockAccess().getOutputdataflowdescriptorsAssignment_8_1(), "rule__DataProcessorBlock__OutputdataflowdescriptorsAssignment_8_1");
			builder.put(grammarAccess.getDataProcessorBlockAccess().getAnomynousoutputdataflowdescriptorsAssignment_8_2(), "rule__DataProcessorBlock__AnomynousoutputdataflowdescriptorsAssignment_8_2");
			builder.put(grammarAccess.getDataProcessorBlockAccess().getAnomynousoutputdataflowdescriptorsAssignment_9_1(), "rule__DataProcessorBlock__AnomynousoutputdataflowdescriptorsAssignment_9_1");
			builder.put(grammarAccess.getDataProcessorBlockAccess().getParametersAssignment_11(), "rule__DataProcessorBlock__ParametersAssignment_11");
			builder.put(grammarAccess.getSynchronizerBlockAccess().getDescriptionAssignment_0_2(), "rule__SynchronizerBlock__DescriptionAssignment_0_2");
			builder.put(grammarAccess.getSynchronizerBlockAccess().getNameAssignment_2(), "rule__SynchronizerBlock__NameAssignment_2");
			builder.put(grammarAccess.getSynchronizerBlockAccess().getInputdataflowdescriptorsAssignment_4_0_0_0(), "rule__SynchronizerBlock__InputdataflowdescriptorsAssignment_4_0_0_0");
			builder.put(grammarAccess.getSynchronizerBlockAccess().getInputdataflowdescriptorsAssignment_4_0_1(), "rule__SynchronizerBlock__InputdataflowdescriptorsAssignment_4_0_1");
			builder.put(grammarAccess.getSynchronizerBlockAccess().getInputdataflowdescriptorsAssignment_4_1(), "rule__SynchronizerBlock__InputdataflowdescriptorsAssignment_4_1");
			builder.put(grammarAccess.getSynchronizerBlockAccess().getAnomynousinputdataflowdescriptorsAssignment_4_2(), "rule__SynchronizerBlock__AnomynousinputdataflowdescriptorsAssignment_4_2");
			builder.put(grammarAccess.getSynchronizerBlockAccess().getAnomynousinputdataflowdescriptorsAssignment_5_1(), "rule__SynchronizerBlock__AnomynousinputdataflowdescriptorsAssignment_5_1");
			builder.put(grammarAccess.getSynchronizerBlockAccess().getOutputdataflowdescriptorsAssignment_8_0_0_0(), "rule__SynchronizerBlock__OutputdataflowdescriptorsAssignment_8_0_0_0");
			builder.put(grammarAccess.getSynchronizerBlockAccess().getOutputdataflowdescriptorsAssignment_8_0_1(), "rule__SynchronizerBlock__OutputdataflowdescriptorsAssignment_8_0_1");
			builder.put(grammarAccess.getSynchronizerBlockAccess().getOutputdataflowdescriptorsAssignment_8_1(), "rule__SynchronizerBlock__OutputdataflowdescriptorsAssignment_8_1");
			builder.put(grammarAccess.getSynchronizerBlockAccess().getAnomynousoutputdataflowdescriptorsAssignment_8_2(), "rule__SynchronizerBlock__AnomynousoutputdataflowdescriptorsAssignment_8_2");
			builder.put(grammarAccess.getSynchronizerBlockAccess().getAnomynousoutputdataflowdescriptorsAssignment_9_1(), "rule__SynchronizerBlock__AnomynousoutputdataflowdescriptorsAssignment_9_1");
			builder.put(grammarAccess.getSynchronizerBlockAccess().getParametersAssignment_11(), "rule__SynchronizerBlock__ParametersAssignment_11");
			builder.put(grammarAccess.getDefinitionInstructionAccess().getNameAssignment_1(), "rule__DefinitionInstruction__NameAssignment_1");
			builder.put(grammarAccess.getDefinitionInstructionAccess().getDataflowdescriptorAssignment_2_1(), "rule__DefinitionInstruction__DataflowdescriptorAssignment_2_1");
			builder.put(grammarAccess.getPreProcessorAssignationAccess().getOutputsAssignment_0_0(), "rule__PreProcessorAssignation__OutputsAssignment_0_0");
			builder.put(grammarAccess.getPreProcessorAssignationAccess().getOutputsAssignment_1(), "rule__PreProcessorAssignation__OutputsAssignment_1");
			builder.put(grammarAccess.getPreProcessorAssignationAccess().getInputsAssignment_4_0(), "rule__PreProcessorAssignation__InputsAssignment_4_0");
			builder.put(grammarAccess.getPreProcessorAssignationAccess().getInputsAssignment_5(), "rule__PreProcessorAssignation__InputsAssignment_5");
			builder.put(grammarAccess.getPreProcessorAssignationAccess().getInterfacerdescriptorAssignment_7(), "rule__PreProcessorAssignation__InterfacerdescriptorAssignment_7");
			builder.put(grammarAccess.getProcessorAssignationAccess().getOutputsAssignment_0_0(), "rule__ProcessorAssignation__OutputsAssignment_0_0");
			builder.put(grammarAccess.getProcessorAssignationAccess().getOutputsAssignment_1(), "rule__ProcessorAssignation__OutputsAssignment_1");
			builder.put(grammarAccess.getProcessorAssignationAccess().getInputsAssignment_4_0(), "rule__ProcessorAssignation__InputsAssignment_4_0");
			builder.put(grammarAccess.getProcessorAssignationAccess().getInputsAssignment_5(), "rule__ProcessorAssignation__InputsAssignment_5");
			builder.put(grammarAccess.getProcessorAssignationAccess().getInterfacerdescriptorAssignment_7(), "rule__ProcessorAssignation__InterfacerdescriptorAssignment_7");
			builder.put(grammarAccess.getSynchronizerAssignationAccess().getOutputsAssignment_0_0(), "rule__SynchronizerAssignation__OutputsAssignment_0_0");
			builder.put(grammarAccess.getSynchronizerAssignationAccess().getOutputsAssignment_1(), "rule__SynchronizerAssignation__OutputsAssignment_1");
			builder.put(grammarAccess.getSynchronizerAssignationAccess().getInputsAssignment_4_0(), "rule__SynchronizerAssignation__InputsAssignment_4_0");
			builder.put(grammarAccess.getSynchronizerAssignationAccess().getInputsAssignment_5(), "rule__SynchronizerAssignation__InputsAssignment_5");
			builder.put(grammarAccess.getSynchronizerAssignationAccess().getInterfacerdescriptorAssignment_7(), "rule__SynchronizerAssignation__InterfacerdescriptorAssignment_7");
			builder.put(grammarAccess.getOutputAssignationAccess().getOutputsAssignment_0_0(), "rule__OutputAssignation__OutputsAssignment_0_0");
			builder.put(grammarAccess.getOutputAssignationAccess().getOutputsAssignment_1(), "rule__OutputAssignation__OutputsAssignment_1");
			builder.put(grammarAccess.getOutputAssignationAccess().getInputsAssignment_3_0(), "rule__OutputAssignation__InputsAssignment_3_0");
			builder.put(grammarAccess.getOutputAssignationAccess().getInputsAssignment_4(), "rule__OutputAssignation__InputsAssignment_4");
			builder.put(grammarAccess.getDomainParameterBlockAccess().getNameAssignment_2(), "rule__DomainParameterBlock__NameAssignment_2");
			builder.put(grammarAccess.getDomainParameterBlockAccess().getParametersAssignment_4_1(), "rule__DomainParameterBlock__ParametersAssignment_4_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private IDslGrammarAccess grammarAccess;

	@Override
	protected InternalIDslParser createParser() {
		InternalIDslParser result = new InternalIDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public IDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(IDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
