/*
 * generated by Xtext 2.29.0
 */
package n7.intern.v3.xtext.idsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class IDslOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
