/*
 * generated by Xtext 2.25.0.M1
 */
package n7.intern.v2.xtext.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class IDSLScopeProvider extends AbstractIDSLScopeProvider {

}
