/*
 * generated by Xtext 2.29.0
 */
package n7.intern.v3.xtext.idsl.ui;

import com.google.inject.Injector;
import n7.intern.v3.xtext.idsl.ui.internal.IdslActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(IdslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		IdslActivator activator = IdslActivator.getInstance();
		return activator != null ? activator.getInjector(IdslActivator.N7_INTERN_V3_XTEXT_IDSL_IDSL) : null;
	}

}
