/*
 * generated by Xtext 2.29.0
 */
package n7.intern.v3.xtext.idsl.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class IDslScopeProvider extends AbstractIDslScopeProvider {

}
