/*
 * generated by Xtext 2.29.0
 */
package n7.intern.v3.xtext.idsl.ui.tests;

import com.google.inject.Injector;
import n7.intern.v3.xtext.idsl.ui.internal.IdslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class IDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return IdslActivator.getInstance().getInjector("n7.intern.v3.xtext.idsl.IDsl");
	}

}
