/*
 * generated by Xtext 2.29.0
 */
package n7.intern.v3.xtext.domain.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DomainUiModule extends AbstractDomainUiModule {

	public DomainUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
