/*
 * generated by Xtext 2.29.0
 */
package n7.intern.v3.xtext.domain.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import n7.intern.v3.xtext.domain.DomainRuntimeModule;
import n7.intern.v3.xtext.domain.DomainStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DomainIdeSetup extends DomainStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DomainRuntimeModule(), new DomainIdeModule()));
	}
	
}
