/*
 * generated by Xtext 2.29.0
 */
package n7.intern.v3.xtext.idsl.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class IDslProposalProvider extends AbstractIDslProposalProvider {
}
