/*
 * generated by Xtext 2.25.0.M1
 */
package n7.intern.v2.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class IDSLStandaloneSetup extends IDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new IDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
