/*
 * generated by Xtext 2.29.0
 */
package n7.intern.v3.xtext.domain.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class DomainGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class DomainFrameworkElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "n7.intern.v3.xtext.domain.Domain.DomainFramework");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Keyword cDescriptionKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cDescriptionAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_0_2_0 = (RuleCall)cDescriptionAssignment_0_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_0_3 = (Keyword)cGroup_0.eContents().get(3);
		private final Keyword cDomainKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cSetupsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cSetupsSetupParserRuleCall_4_0 = (RuleCall)cSetupsAssignment_4.eContents().get(0);
		private final Assignment cFunction_definitionsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cFunction_definitionsFunctionDefinitionParserRuleCall_5_0 = (RuleCall)cFunction_definitionsAssignment_5.eContents().get(0);
		private final Alternatives cAlternatives_6 = (Alternatives)cGroup.eContents().get(6);
		private final Assignment cParametersAssignment_6_0 = (Assignment)cAlternatives_6.eContents().get(0);
		private final RuleCall cParametersTypedParameterParserRuleCall_6_0_0 = (RuleCall)cParametersAssignment_6_0.eContents().get(0);
		private final Assignment cParametersAssignment_6_1 = (Assignment)cAlternatives_6.eContents().get(1);
		private final RuleCall cParametersFunctionParameterParserRuleCall_6_1_0 = (RuleCall)cParametersAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//DomainFramework returns DomainFramework hidden(WS, ML_COMMENT, SL_COMMENT):
		//    ('@description''('description=STRING')')?
		//    'domain' name=ID '{'
		//         setups+=Setup
		//         (function_definitions += FunctionDefinition)*
		//         (parameters += TypedParameter| parameters += FunctionParameter)*
		//     '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//('@description''('description=STRING')')?
		//'domain' name=ID '{'
		//     setups+=Setup
		//     (function_definitions += FunctionDefinition)*
		//     (parameters += TypedParameter| parameters += FunctionParameter)*
		// '}'
		public Group getGroup() { return cGroup; }
		
		//('@description''('description=STRING')')?
		public Group getGroup_0() { return cGroup_0; }
		
		//'@description'
		public Keyword getDescriptionKeyword_0_0() { return cDescriptionKeyword_0_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0_1() { return cLeftParenthesisKeyword_0_1; }
		
		//description=STRING
		public Assignment getDescriptionAssignment_0_2() { return cDescriptionAssignment_0_2; }
		
		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_0_2_0() { return cDescriptionSTRINGTerminalRuleCall_0_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_0_3() { return cRightParenthesisKeyword_0_3; }
		
		//'domain'
		public Keyword getDomainKeyword_1() { return cDomainKeyword_1; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//setups+=Setup
		public Assignment getSetupsAssignment_4() { return cSetupsAssignment_4; }
		
		//Setup
		public RuleCall getSetupsSetupParserRuleCall_4_0() { return cSetupsSetupParserRuleCall_4_0; }
		
		//(function_definitions += FunctionDefinition)*
		public Assignment getFunction_definitionsAssignment_5() { return cFunction_definitionsAssignment_5; }
		
		//FunctionDefinition
		public RuleCall getFunction_definitionsFunctionDefinitionParserRuleCall_5_0() { return cFunction_definitionsFunctionDefinitionParserRuleCall_5_0; }
		
		//(parameters += TypedParameter| parameters += FunctionParameter)*
		public Alternatives getAlternatives_6() { return cAlternatives_6; }
		
		//parameters += TypedParameter
		public Assignment getParametersAssignment_6_0() { return cParametersAssignment_6_0; }
		
		//TypedParameter
		public RuleCall getParametersTypedParameterParserRuleCall_6_0_0() { return cParametersTypedParameterParserRuleCall_6_0_0; }
		
		//parameters += FunctionParameter
		public Assignment getParametersAssignment_6_1() { return cParametersAssignment_6_1; }
		
		//FunctionParameter
		public RuleCall getParametersFunctionParameterParserRuleCall_6_1_0() { return cParametersFunctionParameterParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class TypedParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "n7.intern.v3.xtext.domain.Domain.TypedParameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Keyword cDescriptionKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cDescriptionAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_0_2_0 = (RuleCall)cDescriptionAssignment_0_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_0_3 = (Keyword)cGroup_0.eContents().get(3);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeTypeEnumRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cEqualsSignKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Alternatives cAlternatives_3_1 = (Alternatives)cGroup_3.eContents().get(1);
		private final Assignment cDefault_valueAssignment_3_1_0 = (Assignment)cAlternatives_3_1.eContents().get(0);
		private final RuleCall cDefault_valueSTRINGTerminalRuleCall_3_1_0_0 = (RuleCall)cDefault_valueAssignment_3_1_0.eContents().get(0);
		private final Assignment cDefault_valueAssignment_3_1_1 = (Assignment)cAlternatives_3_1.eContents().get(1);
		private final RuleCall cDefault_valueINTTerminalRuleCall_3_1_1_0 = (RuleCall)cDefault_valueAssignment_3_1_1.eContents().get(0);
		private final Assignment cDefault_valueAssignment_3_1_2 = (Assignment)cAlternatives_3_1.eContents().get(2);
		private final RuleCall cDefault_valueNINTTerminalRuleCall_3_1_2_0 = (RuleCall)cDefault_valueAssignment_3_1_2.eContents().get(0);
		private final Assignment cDefault_valueAssignment_3_1_3 = (Assignment)cAlternatives_3_1.eContents().get(3);
		private final RuleCall cDefault_valueBOOLEANTerminalRuleCall_3_1_3_0 = (RuleCall)cDefault_valueAssignment_3_1_3.eContents().get(0);
		private final Assignment cDefault_valueAssignment_3_1_4 = (Assignment)cAlternatives_3_1.eContents().get(4);
		private final RuleCall cDefault_valueFLOATTerminalRuleCall_3_1_4_0 = (RuleCall)cDefault_valueAssignment_3_1_4.eContents().get(0);
		private final Assignment cDefault_valueAssignment_3_1_5 = (Assignment)cAlternatives_3_1.eContents().get(5);
		private final RuleCall cDefault_valueCHARTerminalRuleCall_3_1_5_0 = (RuleCall)cDefault_valueAssignment_3_1_5.eContents().get(0);
		private final Assignment cDefault_valueAssignment_3_1_6 = (Assignment)cAlternatives_3_1.eContents().get(6);
		private final RuleCall cDefault_valueLONGTerminalRuleCall_3_1_6_0 = (RuleCall)cDefault_valueAssignment_3_1_6.eContents().get(0);
		private final Assignment cDefault_valueAssignment_3_1_7 = (Assignment)cAlternatives_3_1.eContents().get(7);
		private final RuleCall cDefault_valueBYTETerminalRuleCall_3_1_7_0 = (RuleCall)cDefault_valueAssignment_3_1_7.eContents().get(0);
		private final Assignment cDefault_valueAssignment_3_1_8 = (Assignment)cAlternatives_3_1.eContents().get(8);
		private final RuleCall cDefault_valueDOUBLETerminalRuleCall_3_1_8_0 = (RuleCall)cDefault_valueAssignment_3_1_8.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cMarkersAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cMarkersAssignationMarkerParserRuleCall_5_0 = (RuleCall)cMarkersAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//TypedParameter returns Parameter:
		//    ('@description''('description=STRING')')?
		//    (type=Type) name=ID ('=' (default_value=STRING|default_value= INT |default_value= NINT | default_value = BOOLEAN | default_value = FLOAT | default_value = CHAR | default_value = LONG | default_value = BYTE | default_value = DOUBLE) )?'{' (markers += AssignationMarker)* '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//('@description''('description=STRING')')?
		//(type=Type) name=ID ('=' (default_value=STRING|default_value= INT |default_value= NINT | default_value = BOOLEAN | default_value = FLOAT | default_value = CHAR | default_value = LONG | default_value = BYTE | default_value = DOUBLE) )?'{' (markers += AssignationMarker)* '}'
		public Group getGroup() { return cGroup; }
		
		//('@description''('description=STRING')')?
		public Group getGroup_0() { return cGroup_0; }
		
		//'@description'
		public Keyword getDescriptionKeyword_0_0() { return cDescriptionKeyword_0_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0_1() { return cLeftParenthesisKeyword_0_1; }
		
		//description=STRING
		public Assignment getDescriptionAssignment_0_2() { return cDescriptionAssignment_0_2; }
		
		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_0_2_0() { return cDescriptionSTRINGTerminalRuleCall_0_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_0_3() { return cRightParenthesisKeyword_0_3; }
		
		//(type=Type)
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//Type
		public RuleCall getTypeTypeEnumRuleCall_1_0() { return cTypeTypeEnumRuleCall_1_0; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//('=' (default_value=STRING|default_value= INT |default_value= NINT | default_value = BOOLEAN | default_value = FLOAT | default_value = CHAR | default_value = LONG | default_value = BYTE | default_value = DOUBLE) )?
		public Group getGroup_3() { return cGroup_3; }
		
		//'='
		public Keyword getEqualsSignKeyword_3_0() { return cEqualsSignKeyword_3_0; }
		
		//(default_value=STRING|default_value= INT |default_value= NINT | default_value = BOOLEAN | default_value = FLOAT | default_value = CHAR | default_value = LONG | default_value = BYTE | default_value = DOUBLE)
		public Alternatives getAlternatives_3_1() { return cAlternatives_3_1; }
		
		//default_value=STRING
		public Assignment getDefault_valueAssignment_3_1_0() { return cDefault_valueAssignment_3_1_0; }
		
		//STRING
		public RuleCall getDefault_valueSTRINGTerminalRuleCall_3_1_0_0() { return cDefault_valueSTRINGTerminalRuleCall_3_1_0_0; }
		
		//default_value= INT
		public Assignment getDefault_valueAssignment_3_1_1() { return cDefault_valueAssignment_3_1_1; }
		
		//INT
		public RuleCall getDefault_valueINTTerminalRuleCall_3_1_1_0() { return cDefault_valueINTTerminalRuleCall_3_1_1_0; }
		
		//default_value= NINT
		public Assignment getDefault_valueAssignment_3_1_2() { return cDefault_valueAssignment_3_1_2; }
		
		//NINT
		public RuleCall getDefault_valueNINTTerminalRuleCall_3_1_2_0() { return cDefault_valueNINTTerminalRuleCall_3_1_2_0; }
		
		//default_value = BOOLEAN
		public Assignment getDefault_valueAssignment_3_1_3() { return cDefault_valueAssignment_3_1_3; }
		
		//BOOLEAN
		public RuleCall getDefault_valueBOOLEANTerminalRuleCall_3_1_3_0() { return cDefault_valueBOOLEANTerminalRuleCall_3_1_3_0; }
		
		//default_value = FLOAT
		public Assignment getDefault_valueAssignment_3_1_4() { return cDefault_valueAssignment_3_1_4; }
		
		//FLOAT
		public RuleCall getDefault_valueFLOATTerminalRuleCall_3_1_4_0() { return cDefault_valueFLOATTerminalRuleCall_3_1_4_0; }
		
		//default_value = CHAR
		public Assignment getDefault_valueAssignment_3_1_5() { return cDefault_valueAssignment_3_1_5; }
		
		//CHAR
		public RuleCall getDefault_valueCHARTerminalRuleCall_3_1_5_0() { return cDefault_valueCHARTerminalRuleCall_3_1_5_0; }
		
		//default_value = LONG
		public Assignment getDefault_valueAssignment_3_1_6() { return cDefault_valueAssignment_3_1_6; }
		
		//LONG
		public RuleCall getDefault_valueLONGTerminalRuleCall_3_1_6_0() { return cDefault_valueLONGTerminalRuleCall_3_1_6_0; }
		
		//default_value = BYTE
		public Assignment getDefault_valueAssignment_3_1_7() { return cDefault_valueAssignment_3_1_7; }
		
		//BYTE
		public RuleCall getDefault_valueBYTETerminalRuleCall_3_1_7_0() { return cDefault_valueBYTETerminalRuleCall_3_1_7_0; }
		
		//default_value = DOUBLE
		public Assignment getDefault_valueAssignment_3_1_8() { return cDefault_valueAssignment_3_1_8; }
		
		//DOUBLE
		public RuleCall getDefault_valueDOUBLETerminalRuleCall_3_1_8_0() { return cDefault_valueDOUBLETerminalRuleCall_3_1_8_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//(markers += AssignationMarker)*
		public Assignment getMarkersAssignment_5() { return cMarkersAssignment_5; }
		
		//AssignationMarker
		public RuleCall getMarkersAssignationMarkerParserRuleCall_5_0() { return cMarkersAssignationMarkerParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class FunctionParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "n7.intern.v3.xtext.domain.Domain.FunctionParameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Keyword cDescriptionKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cDescriptionAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_0_2_0 = (RuleCall)cDescriptionAssignment_0_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_0_3 = (Keyword)cGroup_0.eContents().get(3);
		private final Assignment cFunction_typeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cFunction_typeFunctionDefinitionCrossReference_1_0 = (CrossReference)cFunction_typeAssignment_1.eContents().get(0);
		private final RuleCall cFunction_typeFunctionDefinitionIDTerminalRuleCall_1_0_1 = (RuleCall)cFunction_typeFunctionDefinitionCrossReference_1_0.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cEqualsSignKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDefault_function_valueAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDefault_function_valueQUALIFIED_NAMETerminalRuleCall_3_1_0 = (RuleCall)cDefault_function_valueAssignment_3_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cMarkersAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cMarkersFunctionMarkerParserRuleCall_5_0 = (RuleCall)cMarkersAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//FunctionParameter returns Parameter:
		//    ('@description''('description=STRING')')?
		//    (function_type=[FunctionDefinition]) name=ID ('=' default_function_value=QUALIFIED_NAME )? '{' (markers += FunctionMarker)* '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//('@description''('description=STRING')')?
		//(function_type=[FunctionDefinition]) name=ID ('=' default_function_value=QUALIFIED_NAME )? '{' (markers += FunctionMarker)* '}'
		public Group getGroup() { return cGroup; }
		
		//('@description''('description=STRING')')?
		public Group getGroup_0() { return cGroup_0; }
		
		//'@description'
		public Keyword getDescriptionKeyword_0_0() { return cDescriptionKeyword_0_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0_1() { return cLeftParenthesisKeyword_0_1; }
		
		//description=STRING
		public Assignment getDescriptionAssignment_0_2() { return cDescriptionAssignment_0_2; }
		
		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_0_2_0() { return cDescriptionSTRINGTerminalRuleCall_0_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_0_3() { return cRightParenthesisKeyword_0_3; }
		
		//(function_type=[FunctionDefinition])
		public Assignment getFunction_typeAssignment_1() { return cFunction_typeAssignment_1; }
		
		//[FunctionDefinition]
		public CrossReference getFunction_typeFunctionDefinitionCrossReference_1_0() { return cFunction_typeFunctionDefinitionCrossReference_1_0; }
		
		//ID
		public RuleCall getFunction_typeFunctionDefinitionIDTerminalRuleCall_1_0_1() { return cFunction_typeFunctionDefinitionIDTerminalRuleCall_1_0_1; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//('=' default_function_value=QUALIFIED_NAME )?
		public Group getGroup_3() { return cGroup_3; }
		
		//'='
		public Keyword getEqualsSignKeyword_3_0() { return cEqualsSignKeyword_3_0; }
		
		//default_function_value=QUALIFIED_NAME
		public Assignment getDefault_function_valueAssignment_3_1() { return cDefault_function_valueAssignment_3_1; }
		
		//QUALIFIED_NAME
		public RuleCall getDefault_function_valueQUALIFIED_NAMETerminalRuleCall_3_1_0() { return cDefault_function_valueQUALIFIED_NAMETerminalRuleCall_3_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//(markers += FunctionMarker)*
		public Assignment getMarkersAssignment_5() { return cMarkersAssignment_5; }
		
		//FunctionMarker
		public RuleCall getMarkersFunctionMarkerParserRuleCall_5_0() { return cMarkersFunctionMarkerParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class AssignationMarkerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "n7.intern.v3.xtext.domain.Domain.AssignationMarker");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAssignKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameMarkerIDEnumRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//AssignationMarker returns AssignationMarker:
		//    '@assign''('name=MarkerID')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'@assign''('name=MarkerID')'
		public Group getGroup() { return cGroup; }
		
		//'@assign'
		public Keyword getAssignKeyword_0() { return cAssignKeyword_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//name=MarkerID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//MarkerID
		public RuleCall getNameMarkerIDEnumRuleCall_2_0() { return cNameMarkerIDEnumRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
	}
	public class FunctionMarkerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "n7.intern.v3.xtext.domain.Domain.FunctionMarker");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameMarkerIDEnumRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cBlockAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cBlockFunctionBlockParserRuleCall_5_0 = (RuleCall)cBlockAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//FunctionMarker returns FunctionMarker:
		//    '@do' '('name=MarkerID')' '{'
		//        block=FunctionBlock
		//     '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'@do' '('name=MarkerID')' '{'
		//    block=FunctionBlock
		// '}'
		public Group getGroup() { return cGroup; }
		
		//'@do'
		public Keyword getDoKeyword_0() { return cDoKeyword_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//name=MarkerID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//MarkerID
		public RuleCall getNameMarkerIDEnumRuleCall_2_0() { return cNameMarkerIDEnumRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//block=FunctionBlock
		public Assignment getBlockAssignment_5() { return cBlockAssignment_5; }
		
		//FunctionBlock
		public RuleCall getBlockFunctionBlockParserRuleCall_5_0() { return cBlockFunctionBlockParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class FunctionBlockElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "n7.intern.v3.xtext.domain.Domain.FunctionBlock");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFunctionBlockAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cThisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Group cGroup_3_0 = (Group)cGroup_3.eContents().get(0);
		private final Alternatives cAlternatives_3_0_0 = (Alternatives)cGroup_3_0.eContents().get(0);
		private final Assignment cParametersAssignment_3_0_0_0 = (Assignment)cAlternatives_3_0_0.eContents().get(0);
		private final RuleCall cParametersIDTerminalRuleCall_3_0_0_0_0 = (RuleCall)cParametersAssignment_3_0_0_0.eContents().get(0);
		private final Assignment cParametersAssignment_3_0_0_1 = (Assignment)cAlternatives_3_0_0.eContents().get(1);
		private final RuleCall cParametersDEFAULT_PARAMETERTerminalRuleCall_3_0_0_1_0 = (RuleCall)cParametersAssignment_3_0_0_1.eContents().get(0);
		private final Keyword cCommaKeyword_3_0_1 = (Keyword)cGroup_3_0.eContents().get(1);
		private final Alternatives cAlternatives_3_1 = (Alternatives)cGroup_3.eContents().get(1);
		private final Assignment cParametersAssignment_3_1_0 = (Assignment)cAlternatives_3_1.eContents().get(0);
		private final RuleCall cParametersIDTerminalRuleCall_3_1_0_0 = (RuleCall)cParametersAssignment_3_1_0.eContents().get(0);
		private final Assignment cParametersAssignment_3_1_1 = (Assignment)cAlternatives_3_1.eContents().get(1);
		private final RuleCall cParametersDEFAULT_PARAMETERTerminalRuleCall_3_1_1_0 = (RuleCall)cParametersAssignment_3_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//FunctionBlock returns FunctionBlock:
		//    {FunctionBlock} 'this' '('(((parameters+=ID|parameters+=DEFAULT_PARAMETER) ',')*((parameters+=ID|parameters+=DEFAULT_PARAMETER)))?')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{FunctionBlock} 'this' '('(((parameters+=ID|parameters+=DEFAULT_PARAMETER) ',')*((parameters+=ID|parameters+=DEFAULT_PARAMETER)))?')'
		public Group getGroup() { return cGroup; }
		
		//{FunctionBlock}
		public Action getFunctionBlockAction_0() { return cFunctionBlockAction_0; }
		
		//'this'
		public Keyword getThisKeyword_1() { return cThisKeyword_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//(((parameters+=ID|parameters+=DEFAULT_PARAMETER) ',')*((parameters+=ID|parameters+=DEFAULT_PARAMETER)))?
		public Group getGroup_3() { return cGroup_3; }
		
		//((parameters+=ID|parameters+=DEFAULT_PARAMETER) ',')*
		public Group getGroup_3_0() { return cGroup_3_0; }
		
		//(parameters+=ID|parameters+=DEFAULT_PARAMETER)
		public Alternatives getAlternatives_3_0_0() { return cAlternatives_3_0_0; }
		
		//parameters+=ID
		public Assignment getParametersAssignment_3_0_0_0() { return cParametersAssignment_3_0_0_0; }
		
		//ID
		public RuleCall getParametersIDTerminalRuleCall_3_0_0_0_0() { return cParametersIDTerminalRuleCall_3_0_0_0_0; }
		
		//parameters+=DEFAULT_PARAMETER
		public Assignment getParametersAssignment_3_0_0_1() { return cParametersAssignment_3_0_0_1; }
		
		//DEFAULT_PARAMETER
		public RuleCall getParametersDEFAULT_PARAMETERTerminalRuleCall_3_0_0_1_0() { return cParametersDEFAULT_PARAMETERTerminalRuleCall_3_0_0_1_0; }
		
		//','
		public Keyword getCommaKeyword_3_0_1() { return cCommaKeyword_3_0_1; }
		
		//((parameters+=ID|parameters+=DEFAULT_PARAMETER))
		public Alternatives getAlternatives_3_1() { return cAlternatives_3_1; }
		
		//parameters+=ID
		public Assignment getParametersAssignment_3_1_0() { return cParametersAssignment_3_1_0; }
		
		//ID
		public RuleCall getParametersIDTerminalRuleCall_3_1_0_0() { return cParametersIDTerminalRuleCall_3_1_0_0; }
		
		//parameters+=DEFAULT_PARAMETER
		public Assignment getParametersAssignment_3_1_1() { return cParametersAssignment_3_1_1; }
		
		//DEFAULT_PARAMETER
		public RuleCall getParametersDEFAULT_PARAMETERTerminalRuleCall_3_1_1_0() { return cParametersDEFAULT_PARAMETERTerminalRuleCall_3_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}
	public class FunctionDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "n7.intern.v3.xtext.domain.Domain.FunctionDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Keyword cDescriptionKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cDescriptionAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_0_2_0 = (RuleCall)cDescriptionAssignment_0_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_0_3 = (Keyword)cGroup_0.eContents().get(3);
		private final Keyword cDefKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Group cGroup_4_0 = (Group)cGroup_4.eContents().get(0);
		private final Assignment cInputsAssignment_4_0_0 = (Assignment)cGroup_4_0.eContents().get(0);
		private final RuleCall cInputsTypeEnumRuleCall_4_0_0_0 = (RuleCall)cInputsAssignment_4_0_0.eContents().get(0);
		private final Keyword cCommaKeyword_4_0_1 = (Keyword)cGroup_4_0.eContents().get(1);
		private final Assignment cInputsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cInputsTypeEnumRuleCall_4_1_0 = (RuleCall)cInputsAssignment_4_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cColonKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Group cGroup_6_1 = (Group)cGroup_6.eContents().get(1);
		private final Assignment cOutputsAssignment_6_1_0 = (Assignment)cGroup_6_1.eContents().get(0);
		private final RuleCall cOutputsTypeEnumRuleCall_6_1_0_0 = (RuleCall)cOutputsAssignment_6_1_0.eContents().get(0);
		private final Keyword cCommaKeyword_6_1_1 = (Keyword)cGroup_6_1.eContents().get(1);
		private final Assignment cOutputsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cOutputsTypeEnumRuleCall_6_2_0 = (RuleCall)cOutputsAssignment_6_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cValuesAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cValuesFunctionValueParserRuleCall_8_0 = (RuleCall)cValuesAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//FunctionDefinition returns FunctionDefinition:
		//    ('@description''('description=STRING')')?
		//    'def' name = ID '(' ((inputs+= Type',')*(inputs+= Type))? ')' (':' (outputs+= Type',')*(outputs+= Type))? '{' (values+=FunctionValue)+ '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//('@description''('description=STRING')')?
		//'def' name = ID '(' ((inputs+= Type',')*(inputs+= Type))? ')' (':' (outputs+= Type',')*(outputs+= Type))? '{' (values+=FunctionValue)+ '}'
		public Group getGroup() { return cGroup; }
		
		//('@description''('description=STRING')')?
		public Group getGroup_0() { return cGroup_0; }
		
		//'@description'
		public Keyword getDescriptionKeyword_0_0() { return cDescriptionKeyword_0_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0_1() { return cLeftParenthesisKeyword_0_1; }
		
		//description=STRING
		public Assignment getDescriptionAssignment_0_2() { return cDescriptionAssignment_0_2; }
		
		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_0_2_0() { return cDescriptionSTRINGTerminalRuleCall_0_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_0_3() { return cRightParenthesisKeyword_0_3; }
		
		//'def'
		public Keyword getDefKeyword_1() { return cDefKeyword_1; }
		
		//name = ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3() { return cLeftParenthesisKeyword_3; }
		
		//((inputs+= Type',')*(inputs+= Type))?
		public Group getGroup_4() { return cGroup_4; }
		
		//(inputs+= Type',')*
		public Group getGroup_4_0() { return cGroup_4_0; }
		
		//inputs+= Type
		public Assignment getInputsAssignment_4_0_0() { return cInputsAssignment_4_0_0; }
		
		//Type
		public RuleCall getInputsTypeEnumRuleCall_4_0_0_0() { return cInputsTypeEnumRuleCall_4_0_0_0; }
		
		//','
		public Keyword getCommaKeyword_4_0_1() { return cCommaKeyword_4_0_1; }
		
		//(inputs+= Type)
		public Assignment getInputsAssignment_4_1() { return cInputsAssignment_4_1; }
		
		//Type
		public RuleCall getInputsTypeEnumRuleCall_4_1_0() { return cInputsTypeEnumRuleCall_4_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
		
		//(':' (outputs+= Type',')*(outputs+= Type))?
		public Group getGroup_6() { return cGroup_6; }
		
		//':'
		public Keyword getColonKeyword_6_0() { return cColonKeyword_6_0; }
		
		//(outputs+= Type',')*
		public Group getGroup_6_1() { return cGroup_6_1; }
		
		//outputs+= Type
		public Assignment getOutputsAssignment_6_1_0() { return cOutputsAssignment_6_1_0; }
		
		//Type
		public RuleCall getOutputsTypeEnumRuleCall_6_1_0_0() { return cOutputsTypeEnumRuleCall_6_1_0_0; }
		
		//','
		public Keyword getCommaKeyword_6_1_1() { return cCommaKeyword_6_1_1; }
		
		//(outputs+= Type)
		public Assignment getOutputsAssignment_6_2() { return cOutputsAssignment_6_2; }
		
		//Type
		public RuleCall getOutputsTypeEnumRuleCall_6_2_0() { return cOutputsTypeEnumRuleCall_6_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7() { return cLeftCurlyBracketKeyword_7; }
		
		//(values+=FunctionValue)+
		public Assignment getValuesAssignment_8() { return cValuesAssignment_8; }
		
		//FunctionValue
		public RuleCall getValuesFunctionValueParserRuleCall_8_0() { return cValuesFunctionValueParserRuleCall_8_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class FunctionValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "n7.intern.v3.xtext.domain.Domain.FunctionValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cInstructionsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cInstructionsSetupBlockParserRuleCall_2_0 = (RuleCall)cInstructionsAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//FunctionValue returns FunctionValue:
		//    name=ID '{'(instructions+=SetupBlock)+ '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID '{'(instructions+=SetupBlock)+ '}'
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//(instructions+=SetupBlock)+
		public Assignment getInstructionsAssignment_2() { return cInstructionsAssignment_2; }
		
		//SetupBlock
		public RuleCall getInstructionsSetupBlockParserRuleCall_2_0() { return cInstructionsSetupBlockParserRuleCall_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class SetupBlockElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "n7.intern.v3.xtext.domain.Domain.SetupBlock");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCommercialAtKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cLanguageAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLanguageLanguageEnumRuleCall_1_0 = (RuleCall)cLanguageAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cInstructionsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cInstructionsStringInstructionParserRuleCall_3_0 = (RuleCall)cInstructionsAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//SetupBlock returns SetupBlock:
		//    '@' language=Language '{' instructions += StringInstruction'}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'@' language=Language '{' instructions += StringInstruction'}'
		public Group getGroup() { return cGroup; }
		
		//'@'
		public Keyword getCommercialAtKeyword_0() { return cCommercialAtKeyword_0; }
		
		//language=Language
		public Assignment getLanguageAssignment_1() { return cLanguageAssignment_1; }
		
		//Language
		public RuleCall getLanguageLanguageEnumRuleCall_1_0() { return cLanguageLanguageEnumRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//instructions += StringInstruction
		public Assignment getInstructionsAssignment_3() { return cInstructionsAssignment_3; }
		
		//StringInstruction
		public RuleCall getInstructionsStringInstructionParserRuleCall_3_0() { return cInstructionsStringInstructionParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class SetupElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "n7.intern.v3.xtext.domain.Domain.Setup");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSetupKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cInstructionsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cInstructionsSetupBlockParserRuleCall_2_0 = (RuleCall)cInstructionsAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Setup returns Setup:
		//    'setup' '{'(instructions+=SetupBlock)+'}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'setup' '{'(instructions+=SetupBlock)+'}'
		public Group getGroup() { return cGroup; }
		
		//'setup'
		public Keyword getSetupKeyword_0() { return cSetupKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//(instructions+=SetupBlock)+
		public Assignment getInstructionsAssignment_2() { return cInstructionsAssignment_2; }
		
		//SetupBlock
		public RuleCall getInstructionsSetupBlockParserRuleCall_2_0() { return cInstructionsSetupBlockParserRuleCall_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class StringInstructionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "n7.intern.v3.xtext.domain.Domain.StringInstruction");
		private final Assignment cContentAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cContentUNQUOTEDSTRINGTerminalRuleCall_0 = (RuleCall)cContentAssignment.eContents().get(0);
		
		//StringInstruction returns StringInstruction:
		//    content = UNQUOTEDSTRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//content = UNQUOTEDSTRING
		public Assignment getContentAssignment() { return cContentAssignment; }
		
		//UNQUOTEDSTRING
		public RuleCall getContentUNQUOTEDSTRINGTerminalRuleCall_0() { return cContentUNQUOTEDSTRINGTerminalRuleCall_0; }
	}
	
	public class LanguageElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "n7.intern.v3.xtext.domain.Domain.Language");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cPythonEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cPythonPythonKeyword_0_0 = (Keyword)cPythonEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cJavaEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cJavaJavaKeyword_1_0 = (Keyword)cJavaEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cCEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cCCKeyword_2_0 = (Keyword)cCEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum Language:
		//    python='python' | java = 'java' | c='c'
		//;
		public EnumRule getRule() { return rule; }
		
		//python='python' | java = 'java' | c='c'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//python='python'
		public EnumLiteralDeclaration getPythonEnumLiteralDeclaration_0() { return cPythonEnumLiteralDeclaration_0; }
		
		//'python'
		public Keyword getPythonPythonKeyword_0_0() { return cPythonPythonKeyword_0_0; }
		
		//java = 'java'
		public EnumLiteralDeclaration getJavaEnumLiteralDeclaration_1() { return cJavaEnumLiteralDeclaration_1; }
		
		//'java'
		public Keyword getJavaJavaKeyword_1_0() { return cJavaJavaKeyword_1_0; }
		
		//c='c'
		public EnumLiteralDeclaration getCEnumLiteralDeclaration_2() { return cCEnumLiteralDeclaration_2; }
		
		//'c'
		public Keyword getCCKeyword_2_0() { return cCCKeyword_2_0; }
	}
	public class MarkerIDElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "n7.intern.v3.xtext.domain.Domain.MarkerID");
		private final EnumLiteralDeclaration cINTERPOLATIONEnumLiteralDeclaration = (EnumLiteralDeclaration)rule.eContents().get(1);
		private final Keyword cINTERPOLATIONInterpolationKeyword_0 = (Keyword)cINTERPOLATIONEnumLiteralDeclaration.eContents().get(0);
		
		//enum MarkerID:
		//    INTERPOLATION='Interpolation'
		//;
		public EnumRule getRule() { return rule; }
		
		//INTERPOLATION='Interpolation'
		public EnumLiteralDeclaration getINTERPOLATIONEnumLiteralDeclaration() { return cINTERPOLATIONEnumLiteralDeclaration; }
		
		//'Interpolation'
		public Keyword getINTERPOLATIONInterpolationKeyword_0() { return cINTERPOLATIONInterpolationKeyword_0; }
	}
	public class TypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "n7.intern.v3.xtext.domain.Domain.Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cStringEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cStringStringKeyword_0_0 = (Keyword)cStringEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cByteEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cByteByteKeyword_1_0 = (Keyword)cByteEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cShortEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cShortShortKeyword_2_0 = (Keyword)cShortEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cIntEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cIntIntKeyword_3_0 = (Keyword)cIntEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cLongEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cLongLongKeyword_4_0 = (Keyword)cLongEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cFloatEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cFloatFloatKeyword_5_0 = (Keyword)cFloatEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cDoubleEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cDoubleDoubleKeyword_6_0 = (Keyword)cDoubleEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cCharEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cCharCharKeyword_7_0 = (Keyword)cCharEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cBooleanEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cBooleanBooleanKeyword_8_0 = (Keyword)cBooleanEnumLiteralDeclaration_8.eContents().get(0);
		
		//enum Type :
		//    string='string'| byte = 'byte'| short = 'short'| int = 'int'| long = 'long'| float = 'float' | double = 'double' | char = 'char' | boolean = 'boolean'
		//;
		public EnumRule getRule() { return rule; }
		
		//string='string'| byte = 'byte'| short = 'short'| int = 'int'| long = 'long'| float = 'float' | double = 'double' | char = 'char' | boolean = 'boolean'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//string='string'
		public EnumLiteralDeclaration getStringEnumLiteralDeclaration_0() { return cStringEnumLiteralDeclaration_0; }
		
		//'string'
		public Keyword getStringStringKeyword_0_0() { return cStringStringKeyword_0_0; }
		
		//byte = 'byte'
		public EnumLiteralDeclaration getByteEnumLiteralDeclaration_1() { return cByteEnumLiteralDeclaration_1; }
		
		//'byte'
		public Keyword getByteByteKeyword_1_0() { return cByteByteKeyword_1_0; }
		
		//short = 'short'
		public EnumLiteralDeclaration getShortEnumLiteralDeclaration_2() { return cShortEnumLiteralDeclaration_2; }
		
		//'short'
		public Keyword getShortShortKeyword_2_0() { return cShortShortKeyword_2_0; }
		
		//int = 'int'
		public EnumLiteralDeclaration getIntEnumLiteralDeclaration_3() { return cIntEnumLiteralDeclaration_3; }
		
		//'int'
		public Keyword getIntIntKeyword_3_0() { return cIntIntKeyword_3_0; }
		
		//long = 'long'
		public EnumLiteralDeclaration getLongEnumLiteralDeclaration_4() { return cLongEnumLiteralDeclaration_4; }
		
		//'long'
		public Keyword getLongLongKeyword_4_0() { return cLongLongKeyword_4_0; }
		
		//float = 'float'
		public EnumLiteralDeclaration getFloatEnumLiteralDeclaration_5() { return cFloatEnumLiteralDeclaration_5; }
		
		//'float'
		public Keyword getFloatFloatKeyword_5_0() { return cFloatFloatKeyword_5_0; }
		
		//double = 'double'
		public EnumLiteralDeclaration getDoubleEnumLiteralDeclaration_6() { return cDoubleEnumLiteralDeclaration_6; }
		
		//'double'
		public Keyword getDoubleDoubleKeyword_6_0() { return cDoubleDoubleKeyword_6_0; }
		
		//char = 'char'
		public EnumLiteralDeclaration getCharEnumLiteralDeclaration_7() { return cCharEnumLiteralDeclaration_7; }
		
		//'char'
		public Keyword getCharCharKeyword_7_0() { return cCharCharKeyword_7_0; }
		
		//boolean = 'boolean'
		public EnumLiteralDeclaration getBooleanEnumLiteralDeclaration_8() { return cBooleanEnumLiteralDeclaration_8; }
		
		//'boolean'
		public Keyword getBooleanBooleanKeyword_8_0() { return cBooleanBooleanKeyword_8_0; }
	}
	
	private final DomainFrameworkElements pDomainFramework;
	private final TypedParameterElements pTypedParameter;
	private final FunctionParameterElements pFunctionParameter;
	private final AssignationMarkerElements pAssignationMarker;
	private final FunctionMarkerElements pFunctionMarker;
	private final FunctionBlockElements pFunctionBlock;
	private final TerminalRule tDEFAULT_PARAMETER;
	private final FunctionDefinitionElements pFunctionDefinition;
	private final FunctionValueElements pFunctionValue;
	private final SetupBlockElements pSetupBlock;
	private final SetupElements pSetup;
	private final StringInstructionElements pStringInstruction;
	private final TerminalRule tUNQUOTEDSTRING;
	private final TerminalRule tQUALIFIED_NAME;
	private final LanguageElements eLanguage;
	private final MarkerIDElements eMarkerID;
	private final TypeElements eType;
	private final TerminalRule tBOOLEAN;
	private final TerminalRule tNINT;
	private final TerminalRule tLONG;
	private final TerminalRule tFLOAT;
	private final TerminalRule tDOUBLE;
	private final TerminalRule tCHAR;
	private final TerminalRule tBYTE;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public DomainGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pDomainFramework = new DomainFrameworkElements();
		this.pTypedParameter = new TypedParameterElements();
		this.pFunctionParameter = new FunctionParameterElements();
		this.pAssignationMarker = new AssignationMarkerElements();
		this.pFunctionMarker = new FunctionMarkerElements();
		this.pFunctionBlock = new FunctionBlockElements();
		this.tDEFAULT_PARAMETER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "n7.intern.v3.xtext.domain.Domain.DEFAULT_PARAMETER");
		this.pFunctionDefinition = new FunctionDefinitionElements();
		this.pFunctionValue = new FunctionValueElements();
		this.pSetupBlock = new SetupBlockElements();
		this.pSetup = new SetupElements();
		this.pStringInstruction = new StringInstructionElements();
		this.tUNQUOTEDSTRING = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "n7.intern.v3.xtext.domain.Domain.UNQUOTEDSTRING");
		this.tQUALIFIED_NAME = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "n7.intern.v3.xtext.domain.Domain.QUALIFIED_NAME");
		this.eLanguage = new LanguageElements();
		this.eMarkerID = new MarkerIDElements();
		this.eType = new TypeElements();
		this.tBOOLEAN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "n7.intern.v3.xtext.domain.Domain.BOOLEAN");
		this.tNINT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "n7.intern.v3.xtext.domain.Domain.NINT");
		this.tLONG = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "n7.intern.v3.xtext.domain.Domain.LONG");
		this.tFLOAT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "n7.intern.v3.xtext.domain.Domain.FLOAT");
		this.tDOUBLE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "n7.intern.v3.xtext.domain.Domain.DOUBLE");
		this.tCHAR = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "n7.intern.v3.xtext.domain.Domain.CHAR");
		this.tBYTE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "n7.intern.v3.xtext.domain.Domain.BYTE");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("n7.intern.v3.xtext.domain.Domain".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//DomainFramework returns DomainFramework hidden(WS, ML_COMMENT, SL_COMMENT):
	//    ('@description''('description=STRING')')?
	//    'domain' name=ID '{'
	//         setups+=Setup
	//         (function_definitions += FunctionDefinition)*
	//         (parameters += TypedParameter| parameters += FunctionParameter)*
	//     '}'
	//;
	public DomainFrameworkElements getDomainFrameworkAccess() {
		return pDomainFramework;
	}
	
	public ParserRule getDomainFrameworkRule() {
		return getDomainFrameworkAccess().getRule();
	}
	
	//TypedParameter returns Parameter:
	//    ('@description''('description=STRING')')?
	//    (type=Type) name=ID ('=' (default_value=STRING|default_value= INT |default_value= NINT | default_value = BOOLEAN | default_value = FLOAT | default_value = CHAR | default_value = LONG | default_value = BYTE | default_value = DOUBLE) )?'{' (markers += AssignationMarker)* '}'
	//;
	public TypedParameterElements getTypedParameterAccess() {
		return pTypedParameter;
	}
	
	public ParserRule getTypedParameterRule() {
		return getTypedParameterAccess().getRule();
	}
	
	//FunctionParameter returns Parameter:
	//    ('@description''('description=STRING')')?
	//    (function_type=[FunctionDefinition]) name=ID ('=' default_function_value=QUALIFIED_NAME )? '{' (markers += FunctionMarker)* '}'
	//;
	public FunctionParameterElements getFunctionParameterAccess() {
		return pFunctionParameter;
	}
	
	public ParserRule getFunctionParameterRule() {
		return getFunctionParameterAccess().getRule();
	}
	
	//AssignationMarker returns AssignationMarker:
	//    '@assign''('name=MarkerID')'
	//;
	public AssignationMarkerElements getAssignationMarkerAccess() {
		return pAssignationMarker;
	}
	
	public ParserRule getAssignationMarkerRule() {
		return getAssignationMarkerAccess().getRule();
	}
	
	//FunctionMarker returns FunctionMarker:
	//    '@do' '('name=MarkerID')' '{'
	//        block=FunctionBlock
	//     '}'
	//;
	public FunctionMarkerElements getFunctionMarkerAccess() {
		return pFunctionMarker;
	}
	
	public ParserRule getFunctionMarkerRule() {
		return getFunctionMarkerAccess().getRule();
	}
	
	//FunctionBlock returns FunctionBlock:
	//    {FunctionBlock} 'this' '('(((parameters+=ID|parameters+=DEFAULT_PARAMETER) ',')*((parameters+=ID|parameters+=DEFAULT_PARAMETER)))?')'
	//;
	public FunctionBlockElements getFunctionBlockAccess() {
		return pFunctionBlock;
	}
	
	public ParserRule getFunctionBlockRule() {
		return getFunctionBlockAccess().getRule();
	}
	
	//terminal DEFAULT_PARAMETER returns ecore::EString:
	//    '$'INT
	//;
	public TerminalRule getDEFAULT_PARAMETERRule() {
		return tDEFAULT_PARAMETER;
	}
	
	//FunctionDefinition returns FunctionDefinition:
	//    ('@description''('description=STRING')')?
	//    'def' name = ID '(' ((inputs+= Type',')*(inputs+= Type))? ')' (':' (outputs+= Type',')*(outputs+= Type))? '{' (values+=FunctionValue)+ '}'
	//;
	public FunctionDefinitionElements getFunctionDefinitionAccess() {
		return pFunctionDefinition;
	}
	
	public ParserRule getFunctionDefinitionRule() {
		return getFunctionDefinitionAccess().getRule();
	}
	
	//FunctionValue returns FunctionValue:
	//    name=ID '{'(instructions+=SetupBlock)+ '}'
	//;
	public FunctionValueElements getFunctionValueAccess() {
		return pFunctionValue;
	}
	
	public ParserRule getFunctionValueRule() {
		return getFunctionValueAccess().getRule();
	}
	
	//SetupBlock returns SetupBlock:
	//    '@' language=Language '{' instructions += StringInstruction'}'
	//;
	public SetupBlockElements getSetupBlockAccess() {
		return pSetupBlock;
	}
	
	public ParserRule getSetupBlockRule() {
		return getSetupBlockAccess().getRule();
	}
	
	//Setup returns Setup:
	//    'setup' '{'(instructions+=SetupBlock)+'}'
	//;
	public SetupElements getSetupAccess() {
		return pSetup;
	}
	
	public ParserRule getSetupRule() {
		return getSetupAccess().getRule();
	}
	
	//StringInstruction returns StringInstruction:
	//    content = UNQUOTEDSTRING
	//;
	public StringInstructionElements getStringInstructionAccess() {
		return pStringInstruction;
	}
	
	public ParserRule getStringInstructionRule() {
		return getStringInstructionAccess().getRule();
	}
	
	//terminal UNQUOTEDSTRING:
	//    '>' ( '\\'('b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'>'|'<'|'\\') | !('\\'|'<') )* '<'
	//;
	public TerminalRule getUNQUOTEDSTRINGRule() {
		return tUNQUOTEDSTRING;
	}
	
	//terminal QUALIFIED_NAME:
	//    ID'.'ID
	//;
	public TerminalRule getQUALIFIED_NAMERule() {
		return tQUALIFIED_NAME;
	}
	
	//enum Language:
	//    python='python' | java = 'java' | c='c'
	//;
	public LanguageElements getLanguageAccess() {
		return eLanguage;
	}
	
	public EnumRule getLanguageRule() {
		return getLanguageAccess().getRule();
	}
	
	//enum MarkerID:
	//    INTERPOLATION='Interpolation'
	//;
	public MarkerIDElements getMarkerIDAccess() {
		return eMarkerID;
	}
	
	public EnumRule getMarkerIDRule() {
		return getMarkerIDAccess().getRule();
	}
	
	//enum Type :
	//    string='string'| byte = 'byte'| short = 'short'| int = 'int'| long = 'long'| float = 'float' | double = 'double' | char = 'char' | boolean = 'boolean'
	//;
	public TypeElements getTypeAccess() {
		return eType;
	}
	
	public EnumRule getTypeRule() {
		return getTypeAccess().getRule();
	}
	
	//terminal BOOLEAN returns ecore::EBoolean :
	//    'true' | 'false'
	//;
	public TerminalRule getBOOLEANRule() {
		return tBOOLEAN;
	}
	
	//terminal NINT returns ecore::EInt :
	//    '-' INT
	//;
	public TerminalRule getNINTRule() {
		return tNINT;
	}
	
	//terminal LONG returns ecore::EInt :
	//    (NINT|INT) ('l'|'L')
	//;
	public TerminalRule getLONGRule() {
		return tLONG;
	}
	
	//terminal FLOAT returns ecore::EFloat :
	//    (NINT|INT)('.'INT)?('f'|'F')
	//;
	public TerminalRule getFLOATRule() {
		return tFLOAT;
	}
	
	//terminal DOUBLE returns ecore::EDouble :
	//    (NINT|INT)('.'INT)?('d'|'D')
	//;
	public TerminalRule getDOUBLERule() {
		return tDOUBLE;
	}
	
	//terminal CHAR returns ecore::EChar:
	//     "'" ( '\\'('b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\') | !('\\'|"'") ) "'"
	//;
	public TerminalRule getCHARRule() {
		return tCHAR;
	}
	
	//terminal BYTE returns ecore::EByte:
	//    '0x'((('a'..'z'|'A'..'Z'|'0'..'9')('a'..'z'|'A'..'Z'|'0'..'9'))
	//        |(('a'..'z'|'A'..'Z'|'0'..'9')('a'..'z'|'A'..'Z'|'0'..'9'))(('a'..'z'|'A'..'Z'|'0'..'9')('a'..'z'|'A'..'Z'|'0'..'9'))
	//        |(('a'..'z'|'A'..'Z'|'0'..'9')('a'..'z'|'A'..'Z'|'0'..'9'))(('a'..'z'|'A'..'Z'|'0'..'9')('a'..'z'|'A'..'Z'|'0'..'9'))(('a'..'z'|'A'..'Z'|'0'..'9')('a'..'z'|'A'..'Z'|'0'..'9'))
	//        |(('a'..'z'|'A'..'Z'|'0'..'9')('a'..'z'|'A'..'Z'|'0'..'9'))(('a'..'z'|'A'..'Z'|'0'..'9')('a'..'z'|'A'..'Z'|'0'..'9'))(('a'..'z'|'A'..'Z'|'0'..'9')('a'..'z'|'A'..'Z'|'0'..'9'))(('a'..'z'|'A'..'Z'|'0'..'9')('a'..'z'|'A'..'Z'|'0'..'9'))
	//    )
	//;
	public TerminalRule getBYTERule() {
		return tBYTE;
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
