/*
 * generated by Xtext 2.29.0
 */
package n7.intern.v3.xtext.domain.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DomainAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("n7/intern/v3/xtext/domain/parser/antlr/internal/InternalDomain.tokens");
	}
}
