/*
 * generated by Xtext 2.25.0.M1
 */
package n7.intern.v2.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractIDSLScopeProvider extends DelegatingScopeProvider {
}
