/*
 * generated by Xtext 2.29.0
 */
package n7.intern.v3.xtext.idsl.parser.antlr;

import com.google.inject.Inject;
import n7.intern.v3.xtext.idsl.parser.antlr.internal.InternalIDslParser;
import n7.intern.v3.xtext.idsl.services.IDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class IDslParser extends AbstractAntlrParser {

	@Inject
	private IDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalIDslParser createParser(XtextTokenStream stream) {
		return new InternalIDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "IotFramework";
	}

	public IDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(IDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
