/*
 * generated by Xtext 2.29.0
 */
package n7.intern.v3.xtext.idsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class IDslStandaloneSetup extends IDslStandaloneSetupGenerated {

	public static void doSetup() {
		new IDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
