/*
 * generated by Xtext 2.29.0
 */
package n7.intern.v3.xtext.idsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class IDslRuntimeModule extends AbstractIDslRuntimeModule {
}
