/*
 * generated by Xtext 2.25.0.M1
 */
package n7.intern.v2.xtext;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class IDSLRuntimeModule extends AbstractIDSLRuntimeModule {
}
