/*
 * generated by Xtext 2.29.0
 */
package n7.intern.v3.xtext.idsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class IDslUiModule extends AbstractIDslUiModule {

	public IDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
