/*
 * generated by Xtext 2.29.0
 */
package n7.intern.v3.xtext.domain.ui;

import com.google.inject.Injector;
import n7.intern.v3.xtext.domain.ui.internal.DomainActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DomainExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(DomainActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		DomainActivator activator = DomainActivator.getInstance();
		return activator != null ? activator.getInjector(DomainActivator.N7_INTERN_V3_XTEXT_DOMAIN_DOMAIN) : null;
	}

}
