/*
 * generated by Xtext 2.29.0
 */
package n7.intern.v3.xtext.domain;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DomainRuntimeModule extends AbstractDomainRuntimeModule {
}
