/*
 * generated by Xtext 2.29.0
 */
package n7.intern.v3.xtext.domain.ui.tests;

import com.google.inject.Injector;
import n7.intern.v3.xtext.domain.ui.internal.DomainActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class DomainUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DomainActivator.getInstance().getInjector("n7.intern.v3.xtext.domain.Domain");
	}

}
